### ISSUE TITLE
CLANG_ROUND_TRIP_CC1_ARGS does not work

### ISSUE THREAD

**Issue by jrtc27** [CTSRD-CHERI/llvm-project#521]
Upstream default reverted in b0659d0f2e2759ad19c5366e983bfce84f080c6a.

**Comment by arichardson** [comment]
I've fixed most of these locally, but I think we probably want to wait until the next upstream merge after this one just in case there are more upstream issues that need fixing.

The problem is that the assert can silently change parsing of command line arguments (by dropping some of them). The assertions only check that the generated command line matches after re-parsing, but that is always true if you have forgotten to add a flag in the "generate command line" function.

See also https://reviews.llvm.org/D97462#2677130
