### ISSUE TITLE
Inconsistent behaviour when casting a capability to an integer

### ISSUE THREAD

**Issue by kevin-brodsky-arm** [CTSRD-CHERI/llvm-project#527]
Currently, Clang exhibits two possible behaviours when casting a capability to an integer (e.g. `unsigned long`):
1. It triggers a simple downcast (address extraction) with no warning (unless `-Wpedantic` is passed).
2. It triggers a CToPtr operation with a warning.

It seems that the behaviour differs depending on both the language and the capability mode:

| | C | C++ |
| --- | --- | --- |
| Hybrid | 2 | 1 |
| Purecap | 1 | 1 |

I understand there may be reasons to use a different behaviour in hybrid, but it seems to me that the default behaviour should be the same everywhere, i.e. behaviour 1. Behaviour 2 makes it hard to introduce capabilities in older codebases. That said, it would make sense to have a compiler flag to switch to behaviour 2, at least in hybrid.

**Comment by jrtc27** [comment]
Actually it's more complicated than that and I think your assessment is backwards. There are two classes of interpretations:

1. Integer/pointer <-> capability casts get the address and null derive
2. Integer/pointer <-> capability casts use CToPtr/CFromPtr

Looking at the more complete table:

| | Hybrid | Purecap |
|-|-|-|
| C int2cap | 2 | 1 |
| C cap2int | 2 | 1 |
| C ptr2cap | 2 | 1 |
| C cap2ptr | 2 | 1 |
| C++ int2cap | 2 | 1 |
| C++ cap2int | 1 | 1 |
| C++ ptr2cap | 2 | 1 |
| C++ cap2ptr | 2 | 1 |

(https://cheri-compiler-explorer.cl.cam.ac.uk/z/s687ef)

So, no, the current CToPtr/CFromPtr behaviour *is* correct, as we *must* be able to round-trip pointers/capabilities safely and consistently. The bug is that the C++ capability to integer cast, specifically, does not behave the same as everything else.

The behaviour you want makes some sense, but cannot be supported across all CHERI architectures. In hybrid, pointers/integers cast to capabilities have to be able to be rederived from DDC. On CHERI-MIPS and CHERI-RISC-V, that means a CFromPtr, unless you want an two instruction read DDC + set address sequence, and on Morello, although the architecture lets you have both behaviours, that's not something you can choose in instruction selection, that's a global configuration bit in the processor, and things are going to go badly if the compiler disagrees with what the actual state of CCTLR.DDCBO is. Moreover, the behaviour you want is option 3:

3. Integer/pointer <-> capability casts get the address and "set address derive" from DDC

which is not something CHERI Clang/LLVM has ever supported for any ABI.

**Comment by kevin-brodsky-arm** [comment]
I did not consider the round-trip in my initial assessment. That's a fair point in general, but in the use-case I'm thinking about (i.e. hybrid kernel), casting an integer / 64-bit pointer to a capability should never be done (and we would certainly `-Werror` it if it can be done separately), because you do not want any implicit DDC use (i.e. you always want to control which capability to derive from). As a result, I view the cast from capability to integer as a simple "address extraction". Of course, this should really be done by going through `uintcap_t` or equivalent, and this is what we use for new code, but there is just too much existing code that extracts the address of pointers via a cast.

If changing the existing behaviour is hybrid is deemed too problematic in general, could we at least have a way to change it via a compiler flag?

**Comment by jrtc27** [comment]
Outside of very few cases, casting a user capability to an integer is a sign that you've done something wrong, as you're losing the metadata associated with that address and thus not enforcing the capability model in the kernel<->userspace interface.

**Comment by kevin-brodsky-arm** [comment]
I've given this some more thoughts. I agree with your assessment that in general, such downcasts should be assessed one by one and resolved appropriately; this way, the generation of raw user addresses is kept under control. This is more work to be done immediately on Linux, but it will eventually save debugging time (and make it easier to check correctness).

I am happy with #529 (at least its intention) as a resolution to this issue.
