### ISSUE TITLE
clang-13 frontend error with inline assembler  on openjdk17 morello purecap

### ISSUE THREAD

**Issue by drandynisbet** [CTSRD-CHERI/llvm-project#700]
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      /home/drandynisbet/NEW/morello-jdk17u/src/hotspot/os_cpu/bsd_aarch64/atomic_bsd_aarch64.hpp:144:17: Generating code for declaration 'bare_atomic_fastcall'
#0 0x000000008a14b06c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local64/llvm-morello/bin/../lib/libLLVM-13git.so+0x187306c)
#1 0x000000008a149244 llvm::sys::RunSignalHandlers() (/usr/local64/llvm-morello/bin/../lib/libLLVM-13git.so+0x1871244)
#2 0x000000008a089708 (/usr/local64/llvm-morello/bin/../lib/libLLVM-13git.so+0x17b1708)
#3 0x000000008a089934 (/usr/local64/llvm-morello/bin/../lib/libLLVM-13git.so+0x17b1934)
#4 0x0000000082429484 handle_signal /local/scratch/jenkins/workspace/CheriBSD-pipeline_releng_22.12/cheribsd/lib/libthr/thread/thr_sig.c:0:3
clang-13: error: clang frontend command failed with exit code 134 (use -v to see invocation)

I've attached a tar.gz of the offending snippet of inline assembler and the preprocessed source 
[crash.tar.gz](https://github.com/CTSRD-CHERI/llvm-project/files/11598849/crash.tar.gz)

**Comment by jrtc27** [comment]
You need to use C not r for capability operand constraints, and I don't know how you expect to be able to tie a uint64_t and a void * when they're different register types. I don't know if that's the issue or it's something else, but those jump out as clearly wrong in the code. The latter should give something like "error: unsupported inline asm: input with type 'void *' matching output with type 'long'" though, and the former does somehow seem to work specifically when using register asm, but probably only because it just ignores the constraint given the register is already specified.

**Comment by jrtc27** [comment]
Yeah, ok, make `result` be `register address result __asm__("c0");` and your problem goes away.

Clang and LLVM are pretty notorious for letting you be able to crash the compiler by giving garbage inline assembly input when it comes to register asm.

**Comment by drandynisbet** [comment]
OK many thanks. I'll do a bit more investigation - to check if it is indeed an uint64_t or an address that is expected to be returned. I can verify that making the suggested change (gives warning messages without a crash) and adding
`  return (uint64_t) result;
`
Enables this to compile successfully.
